<?php
/**
 * Created by PhpStorm.
 * User: grace
 * Date: 2017\12\7 0007
 * Time: 13:56
 */

namespace common\service\goods;


use common\models\goods\mongodb\Goods;
use common\models\goods\Category;
use common\service\BaseService;
use common\models\goods\Store;
use common\models\goods\Product;
use common\models\order\UserAddress;
class OrderService extends BaseService
{	
	public $errorMsg;
	
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
	
    
    /**
    * @desc 创建订单
    */
    public function  create($userId,$addressId,$message)
    {
    	$address = UserAddress::findOne($addressId);
    	if(!$address)
    	{
    		$this->errorMsg = '找不到相应的收获地址';
    		return false;
    	}
    	
    }
    
    /**
    * @desc  入库商品详情表
    * @param
    */
    private function createOrderGoods()
    {
    	
    }
}