<?php
namespace frontend\controllers;

use common\libs\CommonController;
use common\service\CategoryService;
use Yii;
use common\models\Options;

/**
 * Base controller
 */
class BaseController extends CommonController
{
    public $category = [];
    
    protected $loginController = ['cart','order','address'];
    
    protected  $userId;
    
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $view = YII::$app->view;
        $options = Options::find()->where(['<','id',4])->select('*')->asArray()->all();
        $view->params['title'] = $options[2]['value'];
        $view->params['keywords'] = $options[0]['value'];
        $view->params['description'] = $options[1]['value'];
        
        if(Yii::$app->user->isGuest)
        {
        	$view->params['isLogin'] = '0';
        }else
        {
        	$view->params['isLogin'] = '1';
        	$this->userId = Yii::$app->user->identity->id;
        }
        if(Yii::$app->request->isAjax)
        {	
        	$this->layout = false;
        	Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        }
    }
    
    
    public function beforeAction($action)
    {
    	$controller =  $action->controller->id;
    	if(in_array($controller, $this->loginController) && Yii::$app->user->isGuest)
    	{
	 		if(Yii::$app->request->isAjax)
	 		{
	 			exit(json_encode(['status' =>1,'msg' =>'请先进行登录操作']));
	 		}else
	 		{
	 			return $this->redirect('/site/login');
	 		}   		
    	}
    	return true;
    }
    
    
    /**
     * 返回json格式数据，将执行 \Yii::$app->end() 操作
     * @param array|string $data 返回的数据，数组或json字符串
     * @return null
     */
    public function renderJson($data = [])
    {
    	if (is_array($data)) {
    		if (!isset($data['code']))
    			$data['code'] = 0;
    		if (!isset($data['msg']))
    			$data['msg'] = '';
    		if (!isset($data['data']))
    			$data['data'] = (object)null;
    		$data = json_encode($data, JSON_UNESCAPED_UNICODE);
    	}
    	$data['status'] = $data['code'];
    	\Yii::$app->response->format = Response::FORMAT_JSON;
    	echo $data;
    	exit();
    	//\Yii::$app->end(0,true);
    	//return null;
    }
	
}