<?php

namespace frontend\controllers;

use common\models\goods\mongodb\Attr;
use common\service\goods\GoodsService;
use Qiniu\json_decode;
use common\models\shop\form\GoodsListForm;
use common\models\shop\form\GoodsForm;

use Yii;

/**
 * goods controller
 */
class GoodsController extends BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    
    public function actionList()
    {
    	return $this->render('list');
    }
    /**
     * Displays homepage.
     * @return mixed
     */
    public function actionDetail()
    {	
    	$id = Yii::$app->request->get('id');
        return $this->render('detail',['id' => $id]);
    }

    
    public function actionGetlist()
    {
    	if(Yii::$app->request->isAjax)
    	{	
    		$size = Yii::$app->request->get('size');
    		$page = Yii::$app->request->get('page');
    		$goodsListForm = new GoodsListForm();
    		$goodsListForm->limit = $size;
			$goodsListForm->page = $page;
			$result = $goodsListForm->search();
    		echo json_encode(['status' => 0,'data' =>$result['data']['list'],'count' => $result['data']['row_count']]);
    	}
    }
    
    
    
    public function actionGetdetail()
    {	
    	$this->layout = false;
    	$id = (string)Yii::$app->request->get('id');
    	$goodsForm = new GoodsForm();
    	$goodsForm->id = $id;
    	$result = $goodsForm->search();
    	return ['data' =>$result['data'],'status' =>$result['code']];
    }
    
    
    

}