<?php

namespace frontend\controllers;

use common\models\goods\mongodb\Goods;
use common\service\CategoryService;


/**
 * goods controller
 */
class GoodsController extends BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionDetail()
    {
        $request = $this->myRequest();

        $data['goods'] = Goods::findOne((string)$request['id']);
        //$data['goods'] = Goods::find()->select(['_id','name','shop_price','image'])->where(['id'=>(string)$request['id']])->asArray()->one();dd($data);
        return $this->render('detail',$data);
    }
}