<?php
/**
 * Created by PhpStorm.
 * User: grace
 * Date: 2017\12\7 0007
 * Time: 13:56
 */

namespace common\service;


use common\models\Ad;

class BannerService extends BaseService
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public static function index($request=[])
    {
        return Ad::find()->select('*')->where(['>','id',0])->asArray()->all();
    }

}