<?php
/**
 * Created by PhpStorm.
 * User: grace
 * Date: 2017\12\8 0008
 * Time: 15:04
 */

namespace common\libs;


use yii\web\Controller;
use Yii;

class CommonController extends Controller
{
    public  $_body = [];
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->_body = json_decode(file_get_contents("php://input"), true);
        if (!$this->_body) {
            $this->_body = Yii::$app->request->post();
            !$this->_body && $this->_body = Yii::$app->request->get();
        }
    }

    /**
     * @param $query
     * 打印最后执行的sql语句
     * 在调用asArray()->one();asArray()->all();之前调用
     *
     */
    public function getLastSql($query)
    {
        $commandQuery = clone $query;
        dd($commandQuery->createCommand()->getRawSql());
    }

    public function myRequest($data = [], $flag = false)
    {
        $request = $this->_body;

        //在不需要的情况下,排除page,page_size参数
        if (!$flag) {
            $request['page'] = isset($request['page']) ? $request['page'] : 1;
            $request['page_size'] = isset($request['page_size']) ? $request['page_size'] : 10;
        }
        return $data ? array_merge($request, $data) : $request;
    }

    /**
     * @param $data
     * @param $par
     * @return array
     * 必传参数检查
     */
    public function check_par($data, $par)
    {
        $info = [];
        foreach ($par as $k2 => $v2) {
            if($data['check_true']){
                (!$data[$v2] && $data[$v2] !== "0")  && appReturn([], 10001, '缺少必要参数:'.$v2 . ' & ' . implode(',',$par));
            }else{
                (!$data[$v2] && $data[$v2] !== "0")  && appReturn([], 10001, '缺少必要参数');
            }

            $info[$v2] = $data[$v2];
        }
        return $info;
    }

}